name: web_project
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Jermaine Oppong <email@example.com>

environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'

dependencies:
  shelf: any
  shelf_static: any

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
